name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read PACKAGES file
        id: packages
        run: | 
            echo 'deps<<EOF' >> "$GITHUB_OUTPUT"
            cat PACKAGES | grep -v ^# >> "$GITHUB_OUTPUT"
            echo 'EOF' >> "$GITHUB_OUTPUT"
      - name: Update r installation
        uses: r-lib/actions/setup-r@v2
      - name: Install dependencies from PACKAGES
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: 'NA'
          packages: |
            dplyr
            jsonlite
            magrittr
            sessioninfo
            testthat
            readr
            tidyr
            rmarkdown
            ${{ steps.packages.outputs.deps }}
      - name: Execute tests.R
        run: |
            library(magrittr)
            fp <- file.path(".github", "classroom", "autograding.json")
            dir.create(dirname(fp))
            testthat::test_file("tests.R") %>%
              as.data.frame() %>% 
              tidyr::separate_wider_regex(test, c("<?", points="[0-9]*", ">?", name=".*")) %>%
              dplyr::transmute(name, points=as.integer(points), run=ifelse(failed, "false", "true"), 
                        setup=sapply(result, function(.x) paste(lapply(.x, as.character), 
                                                                collapse="\n")) %>% 
                              paste0("echo '", ., "'")) %>% 
              list(tests=.) %>% jsonlite::toJSON() %>% write(fp)
        shell: Rscript {0}
      - run: cat .github/classroom/autograding.json
      - name: Github Classroom autograder
        uses: education/autograding@v1
        continue-on-error: true
        